[build]
nixpkgs = [
  "python310",
  "python310Packages.fastapi",
  "python310Packages.uvicorn",
  "python310Packages.sqlalchemy",
  "python310Packages.psycopg2",
  "python310Packages.python-jose",
  "python310Packages.passlib",
  "python310Packages.starlette",
  "python310Packages.jinja2",
  "python310Packages.aiofiles",
  "python310Packages.python-multipart",
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
