[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.uvicorn"]

[phases.install]
cmds = ["pip install --user -r requirements.txt"]

[start]
cmd = "~/.local/bin/uvicorn main:app --host 0.0.0.0 --port $PORT"
